name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
      - gh-pages
  workflow_dispatch:

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.PA_TOKEN }}
          ref: gh-pages

      - name: Python
        run: |
          python -m pip install -r requirements.txt
          python -m pygbag --build .

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PA_TOKEN }}
          branch: gh-pages
          folder: build/web
